package-lock.json
package.json
src/index.js
yarn.lock

install thunk

---

package-lock.json
package.json
src/App.js
src/index.js
src/reducers/manageStore.js
yarn.lock

complete basic setup of index.js and App.js

complete basic setup of index.js and App.js

---

src/actions/fetchCards.js
src/containers/DeckContainer.js
src/reducers/manageStore.js

create fetch call to grab cardsfrom deckofcardsapi

create fetch call to grab cardsfrom deckofcardsapi

---

src/Cards.css
src/components/CurrentCardsTotal.js
src/components/cardsArray.js

create Cards.css to allow card images to be side by side

create Cards.css to allow card images to be side by side

---

src/actions/fetchCards.js
src/components/CurrentCardsTotal.js

deleted  not need codes in current totals

deleted  not need codes in current totals

---

src/actions/fetchDealerCards.js
src/components/DealerCards.js
src/containers/DeckContainer.js
src/reducers/manageStore.js

add dealer cards fetch call and update reducer to handle the new and separate cards.

add dealer cards fetch call and update reducer

---

src/containers/DeckContainer.js
src/reducers/manageStore.js

fixed errors, reducer was erroring and missing fetch cards import

fixed errors, reducer was erroring and missing fetch cards import

---

src/containers/DeckContainer.js

deleted unneeded fetch calls in Deckcontainer

deleted unneeded fetch calls in Deckcontainer

---

src/DealerCards.css
src/DealerCardsMap.css
src/components/DealerCards.js

add CSS to DealerCards to show dealers cards side by side

add CSS to DealerCards to show dealers cards side by side

---

src/actions/sendCardInfo.js
src/components/CurrentCardsTotal.js
src/components/DealerCards.js
src/components/HitCard.js
src/components/cardsArray.js
src/containers/DeckContainer.js
src/reducers/manageStore.js

Create sendCardInfo.js
Convert cardsArray.js to a class component
Convert CurrentCardsTotal.js to a class component
Created mapDispatchToProps in cardsArray.js
Create cards state in DeckContainer

Send Card Info To Backend

---

src/components/CurrentCardsTotal.js
src/components/HitCard.js
src/components/cardsArray.js
src/containers/DeckContainer.js

Both Players and Dealer's cards are sent to backend

Players and Dealer Card Info Gets Sent To Backend

---

src/components/CurrentCardsTotal.js
src/components/HitCard.js
src/containers/DeckContainer.js

Hit Cards Now Render With Images

Hit Cards Have Images

---

src/HitCards.css
src/components/CurrentCardsTotal.js
src/components/DealerCards.js
src/components/HitCard.js
src/containers/DeckContainer.js

Made changes so dealer only renders their first card. Their second card is stored in this.state.cards

Dealer Only Shows One Card

---

src/components/StandButton.js
src/containers/DeckContainer.js

standButton now a functional component. Also passing cards for player and dealersCards for dealer hands to

change standButton to a functional component 

---

src/components/StandButton.js

Changed how cards are calculated in StandButton.js so Kings, Queens, Jacks, and Aces are calculated and added correctly

Dealer and Players Hand Calculates Correctly

---

src/components/StandButton.js
src/containers/DeckContainer.js

*Hit Cards Are Now Calculated With Player's Cards
*Added Messages For If Player Won, Lost, Push, Or Busted

Hit Cards Are Now Calculated With Player's Cards

---

src/actions/fetchAnotherCard.js
src/actions/fetchCards.js
src/actions/fetchDealerCards.js

Changed the fetch calls so that the app will draw from a new deck every time to avoid decks running out of cards

Changed All Deck Fetch Calls To Grab From A New Deck

---

src/actions/fetchAnotherCard.js
src/actions/fetchCards.js
src/actions/fetchDealerCards.js

had to change fetch call for fetching cards, was no longer working

had to change fetch call for fetching cards, was no longer working

---

src/components/CurrentCardsTotal.js

remove REEEE from test

---

src/containers/DeckContainer.js

changing code in handleLoadingDealer to allow New Hand

changing code in handleLoadingDealer to allow New Hand

---

src/components/HitCard.js
src/containers/DeckContainer.js

*Hitting Will Now Alert The User To Their Current Score
*If They Go Over 21, A Message Saying They Busted Will Alert

Hitting Will Now Alert The User To Their Current Score
